{
  "comments": [
    {
      "key": {
        "uuid": "2e150d2f_e5a4e295",
        "filename": "src/config/api-server/vnc_cfg_api_server/resources/logical_router.py",
        "patchSetId": 7
      },
      "lineNbr": 140,
      "author": {
        "id": 720
      },
      "writtenOn": "2020-05-05T14:52:32Z",
      "side": 1,
      "message": "Can you add exception handling it not present ?",
      "revId": "ab73b0eb59bc84580c3be7bae197125905d9d5a7",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    }
  ]
}