{
  "comments": [
    {
      "key": {
        "uuid": "ebb43b40_0ccbe621",
        "filename": "src/config/api-server/vnc_cfg_api_server/resources/virtual_machine_interface.py",
        "patchSetId": 7
      },
      "lineNbr": 1185,
      "author": {
        "id": 515
      },
      "writtenOn": "2020-04-22T20:51:34Z",
      "side": 1,
      "message": "phy_interface_dict.get(\u0027name\u0027) will always be None I guess, we are not doing dbe_read for name field for PI object",
      "revId": "d23ee80821f82ca1f42043af2ae08ebdb128847f",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    }
  ]
}